### PR TITLE
feat: Add page mode filter [WIP]

### PR DESCRIPTION
**Pull request by kewynakshlley**
It creates a util file within a filter that will be used to verify if the page mode is activated and also will check if the command being processed is covered by page mode. Please note that it's a working in progress, and I am struggling to find a place to use this filter.

If I use this on every command, it will be a really repetitive task, once we have a lot of commands. I could use this on the command.rs, but I can't access the context in some parts of the code to check if page mode is activated: 

```rust 
pub fn new(
        name_str: &str,
        commands: Vec<u8>,
        kind: CommandType,
        data_kind: DataType,
        handler: Box<dyn CommandHandler>,
    ) -> Self {
        let data: Vec<u8> = vec![];
        let name: String = name_str.to_string();
        Self {
            commands: Rc::new(commands),
            name: Rc::new(name),
            data,
            kind,
            data_kind,
            handler,
        }
    }
```

I thought about placing it in the render, but it had a bad smell. Do you have any suggestion for this?

### CODE REVIEW

**Comment by zachzurn** [comment]
Is the goal of this to prevent these commands when page mode is not active?

**Comment by zachzurn** [comment]
Suggestion is to maybe add it like this. The command parser could then drop the command if disabled returns true.

```rust
pub trait CommandHandler: CloneCommandHandler {
    //Check if command is disabled. Can be used by the parser to drop the command
    fn is_disabled(&self, _command: &Command, _context: &Context) -> bool {
        false
    }
    
... and then do the check is_disabled and don't emit the command from emit_command function

fn emit_command(&mut self, mut cmd: Command) {...
```

**Comment by kewynakshlley** [comment]
Got it! The only problem is that the parser doesn't contain information about the context.

**Comment by kewynakshlley** [comment]
I would be necessary to pass the context here in order to see the context in the parser ...

´´´
let mut command_parser = thermal_parser::new_esc_pos_parser(Box::from(on_new_command), CONTEXT);
´´´

It would change a lot of things in the structure of the code.

**Comment by zachzurn** [comment]
Oh, oops. It's been a while since I worked on this part. I think the check would have to happen in process_command. 

`fn process_command(&mut self, context: &mut Context, command: &Command)`

The parser would still end up parsing and emitting the command, but the renderer would check is_disabled before continuing with the rest of the rendering logic.

I think this doesn't stink too bad :) . It makes sense for the renderer to handle kind of logic. Also if we add a visual debug type renderer we would want to see all commands that are parsed anyway. The parser is still parsing every byte per the spec.

**Comment by kewynakshlley** [comment]
Thanks a lot for the tip, I think now it's in the right place. I am currently working in the ESC S command as well, we have the ESC L that activates page mode, and now we need ESC S to go back to standard mode. 

Also, I am not sure if the filter should make binaries decision. I remember reading that some commands could work in page mode but in a different way.

**Comment by zachzurn** [comment]
Now that I think about it more. Commands are responsible for returning graphics, text, commands, etc. The logic for whether the command returns these should really live inside the command itself. What do you think about that?

I don't like the idea of using static hardcoded logic that changes the behavior of commands.

For example, ESC T (Example with pseudo code)

```rust
impl CommandHandler for Handler {
    fn apply_context(&self, command: &Command, context: &mut Context) {
        if(context.is_page_mode == true) context.page_mode.direction = ""
    }
}
```

This way we also don't need to add the is_disabled check at all and the renderer can continue to work the way it does.

As a somewhat unrelated thought, I think the renderer module is misnamed. It's more of a runtime than a renderer.

**Comment by kewynakshlley** [comment]
That looks good to me … I didn't do this way because I thought that I had to prevent the other commands to be executed. But it makes things simpler. I will close this pr and I will modify the existing commands page mode commands to only be executed if page mode is activated.

**Pull request closed without merging**
